include: [".well-known"]
remote_theme: aljazceru/hacker-gh-pages-theme
plugins:
- jekyll-remote-theme


show_downloads: false
google_analytics: G-S6L2C90HW4
plausible: ark-protocol.com
plausible_script_url: https://analytics.cypherpunk.cloud/js/script.js
